studentOrTeacher()
chooseYourClass()
//chooseYourLanguage() //appelé dans chooseYourClass()
//chooseYourTeacher()  //appelé dans chooseYourLanguage()
//reserveYourClass  //appelé dans chooseYourTeacher()